"""
This file provides documentation for the Firebase data models used in the application.
All actual data operations are handled through the firebase_db.py module.
"""

# PRVisit model definition in Firestore
"""
Collection: pr_visits
Document fields:
- id: (string, auto-generated by Firestore)
- pr_name: (string, required)
- visit_start_time: (timestamp)
- client_name: (string, required)
- manager_incharge: (string, required)
- visit_status: (string, default: 'Waiting to start')
- notes: (string, optional)
- created_at: (timestamp, auto-populated by SERVER_TIMESTAMP)
- updated_at: (timestamp, auto-populated by SERVER_TIMESTAMP)
"""

# TCActivity model definition in Firestore
"""
Collection: tc_activities
Document fields:
- id: (string, auto-generated by Firestore)
- telecaller_name: (string, required)
- manager_incharge: (string, required)
- calls_made: (number, default: 0)
- visits_booked: (number, default: 0)
- visits_confirmed: (number, default: 0)
- leads_acquired: (number, default: 0)
- bucket_leads: (number, default: 0)
- created_at: (timestamp, auto-populated by SERVER_TIMESTAMP)
- updated_at: (timestamp, auto-populated by SERVER_TIMESTAMP)
"""

# TeamMember model definition in Firestore
"""
Collection: team_members
Document fields:
- id: (string, auto-generated by Firestore)
- name: (string, required)
- role: (string, required) - 'PR', 'TC', or 'SM' (Sales Manager)
- active: (boolean, default: true)
- created_at: (timestamp, auto-populated by SERVER_TIMESTAMP)
"""